//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDas.DataManagement.Explorer {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumerationDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumerationDescription() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneDas.DataManagement.Explorer.Resources.EnumerationDescription", typeof(EnumerationDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C# ähnelt.
        /// </summary>
        internal static string CodeLanguage_CSharp {
            get {
                return ResourceManager.GetString("CodeLanguage_CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter code ähnelt.
        /// </summary>
        internal static string CodeType_Filter {
            get {
                return ResourceManager.GetString("CodeType_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared code ähnelt.
        /// </summary>
        internal static string CodeType_Shared {
            get {
                return ResourceManager.GetString("CodeType_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index-based ähnelt.
        /// </summary>
        internal static string CsvRowIndexFormat_Index {
            get {
                return ResourceManager.GetString("CsvRowIndexFormat_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unix time ähnelt.
        /// </summary>
        internal static string CsvRowIndexFormat_Unix {
            get {
                return ResourceManager.GetString("CsvRowIndexFormat_Unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comma-separated (*.csv) ähnelt.
        /// </summary>
        internal static string FileFormat_CSV {
            get {
                return ResourceManager.GetString("FileFormat_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die imc FAMOS v2 (*.dat) ähnelt.
        /// </summary>
        internal static string FileFormat_FAMOS {
            get {
                return ResourceManager.GetString("FileFormat_FAMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Matlab v7.3 (*.mat) ähnelt.
        /// </summary>
        internal static string FileFormat_MAT73 {
            get {
                return ResourceManager.GetString("FileFormat_MAT73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 file per day ähnelt.
        /// </summary>
        internal static string FileGranularity_Day {
            get {
                return ResourceManager.GetString("FileGranularity_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 file per hour ähnelt.
        /// </summary>
        internal static string FileGranularity_Hour {
            get {
                return ResourceManager.GetString("FileGranularity_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 file per minute ähnelt.
        /// </summary>
        internal static string FileGranularity_Minute_1 {
            get {
                return ResourceManager.GetString("FileGranularity_Minute_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 file per 10 minutes ähnelt.
        /// </summary>
        internal static string FileGranularity_Minute_10 {
            get {
                return ResourceManager.GetString("FileGranularity_Minute_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single file ähnelt.
        /// </summary>
        internal static string FileGranularity_SingleFile {
            get {
                return ResourceManager.GetString("FileGranularity_SingleFile", resourceCulture);
            }
        }
    }
}
