//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDas.Engine {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneDas.Engine.Ressources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The directory contains none or invalid characters. ähnelt.
        /// </summary>
        internal static string OneDasEngine_DirectoryNameInvalid {
            get {
                return ResourceManager.GetString("OneDasEngine_DirectoryNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No PluginActionRequestAttribute was found on the the specified plugin. ähnelt.
        /// </summary>
        internal static string OneDasEngine_MissingPluginActionRequestAttribute {
            get {
                return ResourceManager.GetString("OneDasEngine_MissingPluginActionRequestAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OneDAS state must be ready or run to get a data snapshot. ähnelt.
        /// </summary>
        internal static string OneDasEngine_OneDasStateNotGreaterEqualReady {
            get {
                return ResourceManager.GetString("OneDasEngine_OneDasStateNotGreaterEqualReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The reference clock is not monotonously rising. ähnelt.
        /// </summary>
        internal static string OneDasEngine_ReferenceClockNotMonotonouslyRising {
            get {
                return ResourceManager.GetString("OneDasEngine_ReferenceClockNotMonotonouslyRising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The system is faulted. Acknowledge the error first. ähnelt.
        /// </summary>
        internal static string OneDasEngine_SystemFaultedAcknowledgeFirst {
            get {
                return ResourceManager.GetString("OneDasEngine_SystemFaultedAcknowledgeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured load the project. ähnelt.
        /// </summary>
        internal static string ProjectUpgrader_ErrorLoadingProject {
            get {
                return ResourceManager.GetString("ProjectUpgrader_ErrorLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project&apos;s version is invalid. ähnelt.
        /// </summary>
        internal static string ProjectUpgrader_InvalidProjectVersion {
            get {
                return ResourceManager.GetString("ProjectUpgrader_InvalidProjectVersion", resourceCulture);
            }
        }
    }
}
