//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDas.Extensibility {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneDas.Extensibility.Abstractions.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The instance ID must be equal or greater zero. ähnelt.
        /// </summary>
        internal static string ActionRequest_InstanceIdInvalid {
            get {
                return ResourceManager.GetString("ActionRequest_InstanceIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MaximumDatasetAge is must be between zero and 10000. ähnelt.
        /// </summary>
        internal static string DataReaderExtensionSettingsBase_MaximumDatasetAgeInvalid {
            get {
                return ResourceManager.GetString("DataReaderExtensionSettingsBase_MaximumDatasetAgeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested period has already been written before. ähnelt.
        /// </summary>
        internal static string DataWriterExtensionLogicBase_DateTimeAlreadyWritten {
            get {
                return ResourceManager.GetString("DataWriterExtensionLogicBase_DateTimeAlreadyWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DateTime and TimeSpan arguments must have a granularity &gt;= 1 minute. ähnelt.
        /// </summary>
        internal static string DataWriterExtensionLogicBase_DateTimeGranularityTooHigh {
            get {
                return ResourceManager.GetString("DataWriterExtensionLogicBase_DateTimeGranularityTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file granularity value is invalid. ähnelt.
        /// </summary>
        internal static string DataWriterExtensionSettingsBase_FileGranularityInvalid {
            get {
                return ResourceManager.GetString("DataWriterExtensionSettingsBase_FileGranularityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified extension was not found. ähnelt.
        /// </summary>
        internal static string ExtensionFactory_ExtensionNotFound {
            get {
                return ResourceManager.GetString("ExtensionFactory_ExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find any ExtensionSupporterAttribute. ähnelt.
        /// </summary>
        internal static string ExtensionFactory_NoExtensionSupporterAttributeFound {
            get {
                return ResourceManager.GetString("ExtensionFactory_NoExtensionSupporterAttributeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No matching TExtensionLogic was found. ähnelt.
        /// </summary>
        internal static string ExtensionFactory_NoMatchingTExtensionLogicFound {
            get {
                return ResourceManager.GetString("ExtensionFactory_NoMatchingTExtensionLogicFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified type does not implement the interface IExtensionSupporter. ähnelt.
        /// </summary>
        internal static string ExtensionFactory_TypeDoesNotImplementIExtensionSupporter {
            get {
                return ResourceManager.GetString("ExtensionFactory_TypeDoesNotImplementIExtensionSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument &apos;settingsType&apos; must be a subclass of ExtensionSettingsBase. ähnelt.
        /// </summary>
        internal static string ExtensionFactory_TypeDoesNotInheritFromExtensionSettingsBase {
            get {
                return ResourceManager.GetString("ExtensionFactory_TypeDoesNotInheritFromExtensionSettingsBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExtensionContextAttribute is not defined. ähnelt.
        /// </summary>
        internal static string ExtensionSettingsBase_ExtensionContextAttributeNotDefined {
            get {
                return ResourceManager.GetString("ExtensionSettingsBase_ExtensionContextAttributeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExtensionDescriptionAttribute is not defined. ähnelt.
        /// </summary>
        internal static string ExtensionSettingsBase_ExtensionDescriptionAttributeNotDefined {
            get {
                return ResourceManager.GetString("ExtensionSettingsBase_ExtensionDescriptionAttributeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data storage type is invalid. ähnelt.
        /// </summary>
        internal static string VariableContext_DataStorageTypeInvalid {
            get {
                return ResourceManager.GetString("VariableContext_DataStorageTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided type must be assignable to IDataStorage. ähnelt.
        /// </summary>
        internal static string VariableDescription_DataStorageTypeInvalid {
            get {
                return ResourceManager.GetString("VariableDescription_DataStorageTypeInvalid", resourceCulture);
            }
        }
    }
}
