//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDas.WebServer {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneDas.WebServer.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only one instance of this application is allowed. ähnelt.
        /// </summary>
        internal static string Application_SingeltonInstance {
            get {
                return ResourceManager.GetString("Application_SingeltonInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The calling client is not active. Access denied. ähnelt.
        /// </summary>
        internal static string AuthorizationBehaviorAttribute_NotActive {
            get {
                return ResourceManager.GetString("AuthorizationBehaviorAttribute_NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The calling client is not registered. Access denied. ähnelt.
        /// </summary>
        internal static string AuthorizationBehaviorAttribute_NotRegistered {
            get {
                return ResourceManager.GetString("AuthorizationBehaviorAttribute_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User is not in required role (access denied). ähnelt.
        /// </summary>
        internal static string AuthorizationBehaviorAttribute_UserIsNotInRequiredRole {
            get {
                return ResourceManager.GetString("AuthorizationBehaviorAttribute_UserIsNotInRequiredRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows authentication must be used if role-based authorization is active (access denied). ähnelt.
        /// </summary>
        internal static string AuthorizationBehaviorAttribute_WindowsAuthenticationRequired {
            get {
                return ResourceManager.GetString("AuthorizationBehaviorAttribute_WindowsAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configured slave aliases are not unique. ähnelt.
        /// </summary>
        internal static string CsaReader_CsaNotUnique {
            get {
                return ResourceManager.GetString("CsaReader_CsaNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A timeout occured while reading the configured slave alias of all boxes. ähnelt.
        /// </summary>
        internal static string CsaReader_CsaReadingTimeout {
            get {
                return ResourceManager.GetString("CsaReader_CsaReadingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The OleMessageFilterBehavior attribute only works for synchronous method invocations. ähnelt.
        /// </summary>
        internal static string OleMessageFilterBehaviorAttribute_OnlySynchronousMethodsAllowed {
            get {
                return ResourceManager.GetString("OleMessageFilterBehaviorAttribute_OnlySynchronousMethodsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OneDAS state must be ready or run to get a data snapshot. ähnelt.
        /// </summary>
        internal static string OneDasController_OneDasStateNotGreaterEqualReady {
            get {
                return ResourceManager.GetString("OneDasController_OneDasStateNotGreaterEqualReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OneDAS server must be in state OneDasState.Ready or OneDasState.Run to provide the mapped Hd5Variable set. ähnelt.
        /// </summary>
        internal static string OneDasController_OneDasStateNotGreaterOrEqualReady {
            get {
                return ResourceManager.GetString("OneDasController_OneDasStateNotGreaterOrEqualReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The reference clock is not monotonously rising. ähnelt.
        /// </summary>
        internal static string OneDasController_ReferenceClockNotMonotonouslyRising {
            get {
                return ResourceManager.GetString("OneDasController_ReferenceClockNotMonotonouslyRising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The directory contains none or invalid characters. ähnelt.
        /// </summary>
        internal static string OneDasManager_DirectoryNameInvalid {
            get {
                return ResourceManager.GetString("OneDasManager_DirectoryNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The system is faulted. Acknowledge the error first. ähnelt.
        /// </summary>
        internal static string OneDasManager_SystemFaultedAcknowledgeFirst {
            get {
                return ResourceManager.GetString("OneDasManager_SystemFaultedAcknowledgeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured load the project. ähnelt.
        /// </summary>
        internal static string ProjectUpgrader_ErrorLoadingProject {
            get {
                return ResourceManager.GetString("ProjectUpgrader_ErrorLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project&apos;s version is invalid. ähnelt.
        /// </summary>
        internal static string ProjectUpgrader_InvalidProjectVersion {
            get {
                return ResourceManager.GetString("ProjectUpgrader_InvalidProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already an active client. Request denied. ähnelt.
        /// </summary>
        internal static string RemoteControlService_AlreadyActiveClient {
            get {
                return ResourceManager.GetString("RemoteControlService_AlreadyActiveClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client is already registered. ähnelt.
        /// </summary>
        internal static string RemoteControlService_AlreadyRegistered {
            get {
                return ResourceManager.GetString("RemoteControlService_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OneDasConfiguration must not be a null reference. ähnelt.
        /// </summary>
        internal static string RemoteControlService_OneDasConfigurationNullReference {
            get {
                return ResourceManager.GetString("RemoteControlService_OneDasConfigurationNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified base directory path is invalid. ähnelt.
        /// </summary>
        internal static string WebClientHub_BaseDirectoryPathIsInvalid {
            get {
                return ResourceManager.GetString("WebClientHub_BaseDirectoryPathIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested channel is inactive or not available in the project. ähnelt.
        /// </summary>
        internal static string WebClientHub_ChannelHubNotFound {
            get {
                return ResourceManager.GetString("WebClientHub_ChannelHubNotFound", resourceCulture);
            }
        }
    }
}
