//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDas.Hdf {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneDas.Hdf.Types.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not commit data type. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotCommitDataType {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotCommitDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not create attribute. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotCreateAttribute {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotCreateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open attribute. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotOpenAttribute {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotOpenAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open dataset. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotOpenDataset {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotOpenDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open or create attribute. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotOpenOrCreateAttribute {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotOpenOrCreateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open or create dataset. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotOpenOrCreateDataset {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotOpenOrCreateDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open or create group. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotOpenOrCreateGroup {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotOpenOrCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not read attribute. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotReadAttribute {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotReadAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not read dataset. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotReadDataset {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotReadDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not select hyperslab. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotSelectHyperslab {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotSelectHyperslab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not write attribute. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotWriteAttribute {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotWriteAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not write dataset. ähnelt.
        /// </summary>
        internal static string HdfHelper_CouldNotWriteDataset {
            get {
                return ResourceManager.GetString("HdfHelper_CouldNotWriteDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data type mismatch. ähnelt.
        /// </summary>
        internal static string HdfHelper_DataTypeMismatch {
            get {
                return ResourceManager.GetString("HdfHelper_DataTypeMismatch", resourceCulture);
            }
        }
    }
}
