//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDas {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneDas.Types.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The instance ID must be equal or greater zero. ähnelt.
        /// </summary>
        internal static string ActionRequest_InstanceIdInvalid {
            get {
                return ResourceManager.GetString("ActionRequest_InstanceIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MaximumDatasetAge is must be between zero and 10000. ähnelt.
        /// </summary>
        internal static string DataReaderPluginSettingsBase_MaximumDatasetAgeInvalid {
            get {
                return ResourceManager.GetString("DataReaderPluginSettingsBase_MaximumDatasetAgeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Array lengths are not matching. ähnelt.
        /// </summary>
        internal static string DataStorage_ArrayLengthMismatch {
            get {
                return ResourceManager.GetString("DataStorage_ArrayLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length must be non-negative. ähnelt.
        /// </summary>
        internal static string DataStorage_LengthNonNegative {
            get {
                return ResourceManager.GetString("DataStorage_LengthNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type of the generic parameter T must be primitive. ähnelt.
        /// </summary>
        internal static string DataStorage_ParameterTNonPrimitive {
            get {
                return ResourceManager.GetString("DataStorage_ParameterTNonPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested period has already been written before. ähnelt.
        /// </summary>
        internal static string DataWriterPluginLogicBase_DateTimeAlreadyWritten {
            get {
                return ResourceManager.GetString("DataWriterPluginLogicBase_DateTimeAlreadyWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DateTime and TimeSpan arguments must have a granularity &gt;= 1 minute. ähnelt.
        /// </summary>
        internal static string DataWriterPluginLogicBase_DateTimeGranularityTooHigh {
            get {
                return ResourceManager.GetString("DataWriterPluginLogicBase_DateTimeGranularityTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file granularity value is invalid. ähnelt.
        /// </summary>
        internal static string DataWriterPluginSettingsBase_FileGranularityInvalid {
            get {
                return ResourceManager.GetString("DataWriterPluginSettingsBase_FileGranularityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No matching TPluginLogic was found. ähnelt.
        /// </summary>
        internal static string PluginManager_NoMatchingTPluginLogicFound {
            get {
                return ResourceManager.GetString("PluginManager_NoMatchingTPluginLogicFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No matching TPluginSettings was found. ähnelt.
        /// </summary>
        internal static string PluginManager_NoMatchingTPluginSettingsFound {
            get {
                return ResourceManager.GetString("PluginManager_NoMatchingTPluginSettingsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find any PluginSupporterAttribute. ähnelt.
        /// </summary>
        internal static string PluginManager_NoPluginSupporterAttributeFound {
            get {
                return ResourceManager.GetString("PluginManager_NoPluginSupporterAttributeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified type does not implement the interface IPluginSupporter. ähnelt.
        /// </summary>
        internal static string PluginManager_TypeDoesNotImplementIPluginSupporter {
            get {
                return ResourceManager.GetString("PluginManager_TypeDoesNotImplementIPluginSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided &apos;pluginSettingsType&apos; is not assignable to an instance of TPluginSettings. ähnelt.
        /// </summary>
        internal static string PluginManager_TypeNotInheritedFromTPluginSettings {
            get {
                return ResourceManager.GetString("PluginManager_TypeNotInheritedFromTPluginSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PluginContextAttribute is not defined. ähnelt.
        /// </summary>
        internal static string PluginSettingsBase_PluginContextAttributeNotDefined {
            get {
                return ResourceManager.GetString("PluginSettingsBase_PluginContextAttributeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PluginDescriptionAttribute is not defined. ähnelt.
        /// </summary>
        internal static string PluginSettingsBase_PluginDescriptionAttributeNotDefined {
            get {
                return ResourceManager.GetString("PluginSettingsBase_PluginDescriptionAttributeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The campaign name is invalid. ähnelt.
        /// </summary>
        internal static string Project_CampaignNameInvalid {
            get {
                return ResourceManager.GetString("Project_CampaignNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The 1st level group name is invalid. ähnelt.
        /// </summary>
        internal static string Project_CampaignPrimaryGroupInvalid {
            get {
                return ResourceManager.GetString("Project_CampaignPrimaryGroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The 2nd level group name is invalid. ähnelt.
        /// </summary>
        internal static string Project_CampaignSecondaryGroupInvalid {
            get {
                return ResourceManager.GetString("Project_CampaignSecondaryGroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more channel names are invalid ähnelt.
        /// </summary>
        internal static string Project_ChannelHubNameInvalid {
            get {
                return ResourceManager.GetString("Project_ChannelHubNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The channel set is invalid: A channel must be unique. ähnelt.
        /// </summary>
        internal static string Project_ChannelHubNotUnqiue {
            get {
                return ResourceManager.GetString("Project_ChannelHubNotUnqiue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data gateway settings IDs are not unique. ähnelt.
        /// </summary>
        internal static string Project_DataGatewaySettingsIdNotUnique {
            get {
                return ResourceManager.GetString("Project_DataGatewaySettingsIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The EcSlaveInfo-Channel-Mapping is invalid: The data types are not matching. ähnelt.
        /// </summary>
        internal static string Project_DataTypeMismatch {
            get {
                return ResourceManager.GetString("Project_DataTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data writer settings IDs are not unique. ähnelt.
        /// </summary>
        internal static string Project_DataWriterSettingsIdNotUnique {
            get {
                return ResourceManager.GetString("Project_DataWriterSettingsIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use A-Z, a-z, 0-9 or _. ähnelt.
        /// </summary>
        internal static string Project_InvalidCharacters {
            get {
                return ResourceManager.GetString("Project_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use A-Z or a-z as first character. ähnelt.
        /// </summary>
        internal static string Project_InvalidLeadingCharacter {
            get {
                return ResourceManager.GetString("Project_InvalidLeadingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name must not be empty. ähnelt.
        /// </summary>
        internal static string Project_NameEmpty {
            get {
                return ResourceManager.GetString("Project_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The campaign version must be equal or greater zero. ähnelt.
        /// </summary>
        internal static string ProjectDescription_InvalidCampaignVersion {
            get {
                return ResourceManager.GetString("ProjectDescription_InvalidCampaignVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The format version must be equal or greater zero. ähnelt.
        /// </summary>
        internal static string ProjectDescription_InvalidFormatVersion {
            get {
                return ResourceManager.GetString("ProjectDescription_InvalidFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument &apos;dataStorageType&apos; must be a subclass of DataStorageBase. ähnelt.
        /// </summary>
        internal static string VariableDescription_TypeNotSubclassOfDataStorage {
            get {
                return ResourceManager.GetString("VariableDescription_TypeNotSubclassOfDataStorage", resourceCulture);
            }
        }
    }
}
